-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 12:57:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PIE3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PIE3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PIE3` DEFAULT CHARACTER SET utf8 ;
USE `PIE3` ;

-- -----------------------------------------------------
-- Table `PIE3`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PIE3`.`publisher` (
  `id_publisher` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_publisher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIE3`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PIE3`.`book` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `subtitle` VARCHAR(255) NULL,
  `publication_year` INT NULL,
  `id_publisher` INT NULL,
  `actual_page` INT NULL,
  `finished` TINYINT NOT NULL,
  PRIMARY KEY (`id_book`),
  INDEX `publisher_idx` (`id_publisher` ASC),
  CONSTRAINT `fk_book_publisher`
    FOREIGN KEY (`id_publisher`)
    REFERENCES `PIE3`.`publisher` (`id_publisher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIE3`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PIE3`.`author` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id_author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIE3`.`book_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PIE3`.`book_author` (
  `id_book` INT NOT NULL,
  `id_author` INT NOT NULL,
  INDEX `book_idx` (`id_book` ASC),
  PRIMARY KEY (`id_book`, `id_author`),
  CONSTRAINT `fk_book_author_book`
    FOREIGN KEY (`id_book`)
    REFERENCES `PIE3`.`book` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_author_author`
    FOREIGN KEY (`id_author`)
    REFERENCES `PIE3`.`author` (`id_author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIE3`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PIE3`.`note` (
  `id_note` INT NOT NULL AUTO_INCREMENT,
  `id_book` INT NOT NULL,
  `init_page` INT NULL,
  `end_page` INT NULL,
  `note` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_note`),
  INDEX `book_idx` (`id_book` ASC),
  CONSTRAINT `fk_note_book`
    FOREIGN KEY (`id_book`)
    REFERENCES `PIE3`.`book` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
